name: SNPrior

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.10
  - numpy=1.26.3
  - pandas=2.1.4
  - scikit-learn=1.4.0
  - scipy=1.11.4
  - matplotlib
  - seaborn
  - tqdm

  # Genomics
  - pgenlib=0.94.1
  - plink2=2.0.0a.6.9

  # Development
  - jupyter
  - pip
  - pip:
      - deap==1.4.1
      - xgboost==2.0.3
      - memory-profiler==0.61.0
      - vcfpy==0.13.8
      - networkx==3.2.1
      - openpyxl==3.1.5
